### ISSUE TITLE
Pass logger data to app main logger

### ISSUE THREAD

**Issue by MKiselev** [2amigos/yii2-usuario#108]
### What steps will reproduce the problem?
Send mail with bad config of mailer.

### What is the expected result?
When error was occured and logged at https://github.com/2amigos/yii2-usuario/blob/master/src/User/Service/UserRegisterService.php#L94 I want see error on main application log component.

### What do you get instead?
Because logger instance was passed by DiC and Logger was not defined as Singleton, the $logger variable is a new instance of Logger class, but not exist app logger.

I was fixed it by configure container like this:
```
Yii::$container->setSingleton(\yii\log\Logger::class, [
    'class' => '\yii\log\Logger',
]);
```
It's work, but I think it's not good idea.

**Comment by tonydspaniard** [comment]
@MKiselev interesting finding, I thought that the DiC should have set the logger as shared instance throughout the entire application thats is why the Service has the declaration of the logger at the constructor so the container could handle that. 

Not having the Logger as a shared object may be a design issue at the Yii Application startup don't you think? 

Us forcing the object to be a shared instance is a hack that Yii may know about, otherwise, we will have to ensure that on the Module's Bootstrap which I think is not a good idea.

**Comment by tonydspaniard** [comment]
@MKiselev maybe I was wrong and maybe, we should instead make a call of `Yii::getLogger()` removing the Logger from the constructor and/or use `Yii::log` directly. What do you think @MKiselev @kartik-v ? Your suggestions are highly valuable.

**Comment by kartik-v** [comment]
Yes it should be simple to use `Yii::getLogger` ... 

For an advanced configure the developer can override the `log` component settings at the user module level as well.

**Comment by kartik-v** [comment]
Yes I feel it should be simple to use `Yii::getLogger` ... 

For an advanced configuration, the developer can override the `log` component settings at the user module level as well.

**Comment by MKiselev** [comment]
@tonydspaniard @kartik-v I was think about this. Pass Logger through DiC it's good way, but in Yii2 very often used static calls od Yii class.

Yii2 Logger component by some historical reason is very individual.

Yii2 supported PSR-7 logging by using: https://github.com/samdark/yii2-psr-log-target

I just wanted ensure that static call of Yii::error() is coverage using PSR-7 logs.

Conclusion: Yii::error() it's normal way to logging in Yii2.
