### ISSUE TITLE
QUESTION: why directory and namespaces Uppercased first letter?

### ISSUE THREAD

**Issue by tsdogs** [2amigos/yii2-usuario#118]
I'm wondering why directory names and namespaces in your projects have the initial character Uppercased?
All yii2 is using lowercase for this.
I know PSR does not impose a standard here, though I'd like to have a "standard" in a project.

**Comment by tonydspaniard** [comment]
@tsdogs because is a fact of a personal taste. Sorry but I strongly dislike lowercase plural namespaces. In some small extensions I didn't mind but when I have to work long time on something, I rather do things I personally like.

Yii2 is in fact one of the few frameworks that use lowercase for its namespace naming conventions but that doesn't mean I have to follow their rules. 

If you hate this decision as I hate lowercase namespace conventions (:smiley:) remember that this project is open source, feel free to fork it, change its namespace convention and add it to your project. I am sorry if my decision disliked you.

**Comment by tsdogs** [comment]
Thanks for taking the time to answer, I supposed it was something like that.

Creating a fork for a thing like this would be insane :-) 
I'd rather concentrate on contributing.
