### ISSUE TITLE
Unable to create an account.

### ISSUE THREAD

**Issue by nakarin4350** [2amigos/yii2-usuario#130]
### What steps will reproduce the problem?
Add Google  or Facebook client
### What is the expected result?
Success create account by using Google  or Facebook  login
### What do you get instead?
Unable to create an account.

I think this is not the same like https://github.com/2amigos/yii2-usuario/issues/49 because I think the root of problem is getUsername in VKontakte.php produce some  [data](https://github.com/2amigos/yii2-usuario/blob/ebea7af6c7b3655bc338587df97bc9baea402c13/src/User/AuthClient/VKontakte.php#L36-L41), but in case of Facebook or Google, they return null. Hence, UserCreateService can't save the model - username is null. Or this is expected behavior because in yii2-user, it allow user to create new username after using facebook/google login.

**Comment by liketomove** [comment]
I'm experiencing the same issue since 1 hour, one solution can be this:
1) Override the SocialNetworkAuthenticateService
2) Put into your createAccount() function this code:
```
switch ($this->client->getId()) {
            case 'facebook':
                $override = true;
                $splitter = explode('@', $this->client->getEmail());
                $username = $splitter[0];
                break;
            case 'google':
                $override = true;
                $splitter = explode('@', $this->client->getEmail());
                $username = $splitter[0];
                break;
            default:
                $username = $this->client->getUserName();
        }
```
3) Finally change the username into make()
`'username' => $username,`

I know, this is a very rough solution and I am pretty sure you are able to do a better code for this.
At least you are able to register your users via social :)

**Comment by tonydspaniard** [comment]
@liketomove is it working like that? If that fixes the issue, do mind posting a PR?

**Comment by liketomove** [comment]
@tonydspaniard yes it works fine, sadly I'm not really experienced on GIT world and I'm very busy on my work in order to find the right time to read guidelines to post a PR.

**Comment by tonydspaniard** [comment]
@liketomove I understand... Currently on quite extensive development mode and I just don't have physical time to do it my self. Hope people understands.

**Comment by tsdogs** [comment]
Imho the problem here resides in the fact that the 'username' cannot be empty and those specific AuthClient implementations return null on ```getUserName()```
It could also have the same problem when ```getUserEmail()``` returns null in other AuthClient classes, though this would be more complicated to solve as we'd have to retrieve user information before creating the account (e-mail in this specific case).

Anyway this would be simply solved by returning the e-mail value as the getUserName() value.

The provided solution above by @liketomove could create some troubles if somebody has an e-mail like goofy@gmail.com and another one is using goofy@miky.com 

If needed I can provide a PR

**Comment by maxxer** [comment]
I think a  PR would me more than welcome 👍

**Comment by agafforov** [comment]
I was getting the same error with Google but I fixed it by overriding \Da\User\AuthClient\Google like this:

`<?php

namespace app\clients;

/**
 * Class Google
 */
class Google extends \Da\User\AuthClient\Google
{
    /**
     * {@inheritdoc}
     */
    public function getEmail()
    {
        $attributes = $this->getUserAttributes();

        if (!empty($attributes['email'])) {
            return $attributes['email'];
        }

        return isset($this->getUserAttributes()['emails'][0]['value'])
            ? $this->getUserAttributes()['emails'][0]['value']
            : null;
    }
}
`
I hope it'll help someone!
