### ISSUE TITLE
How to Add user programatically

### ISSUE THREAD

**Issue by dbd5** [2amigos/yii2-usuario#132]
Hello,

Please advise how one can add a user programmatically without opening any forms for user to complete as may be required in certain use cases.

Thanks

**Comment by tonydspaniard** [comment]
You can do it with the console commands: http://yii2-usuario.readthedocs.io/en/latest/installation/console-commands/

**Comment by dbd5** [comment]
Thanks @tonydspaniard, 

I was actually thinking of coding not console but I'll find a way

Regards

**Comment by tonydspaniard** [comment]
@dbd5 check how the commands do it internally, then you can apply the same logic on your code (the location where to create that user programmatically)

On another note, if you are an admin, you can create as many users as you wish.

**Comment by WeeSee** [comment]
You can try using migrations. I did that with Yii2-user but it should work with Yii2-usario as well:
https://stackoverflow.com/questions/42516985/yii2-user-how-to-create-admin-user-in-batch-mode/47782624#47782624

I wanted to create an admin user after the first migration was executed so that admin can log in an start using the system.

**Comment by dbd5** [comment]
Thanks @tonydspaniard and @WeeSee!

> check how the commands do it internally, then you can apply the same logic
That's what I ended up doing.
