### ISSUE TITLE
Log administrator activities (GDPR)

### ISSUE THREAD

**Issue by maxxer** [2amigos/yii2-usuario#186]
To  be GDPR compliant an application should record login and logout times of administrators. 

Because of this administrator shouldn't be allowed to keep session cookie, they  should login and logout (?) every time. 

What comes to my mind right now is:

1. implement a `user_logins` table for recording **all** logins
1. add a configuration parameter to define *admin* role (or use the existing one which allows impersonation)
1. add a configuration parameter to define the cookie session lifetime for admins
1. add a configuration parameter to define how long login data should be kept (data retention)

Still to define:

- how to *logout* admin sessions: given that someone can just close the browser, how to terminate those sessions? just *close* them after *max-admin-session* time?
- data cleanup: **when** (programmatically) delete the sessions? using a *cron* or a console command?

open for discussion... @tonydspaniard if you can leave your considerations you're welcome

**Comment by Eseperio** [comment]
I have added in my fork some of the common GDPR requirements, like data portability, personal data removal and data processing consent. 
I have added a new page called *privacy* where the users can export their own data (portability) in a csv file. Also can delete their personal data. Deletion can be done in two ways. If `$enableGDPRcompliance` is `true` and `$allowAccountDelete` is true, the whole record will be deleted, but if `$allowAccountDelete` is false, the personal data will be replaced with a customizable word (actually GDPR) and the account becomes blocked. This allows to keep any other information that is still relevant or needed for the application. 

**About recording logins**
[GDPR Art.30](https://gdpr.algolia.com/gdpr-article-30)
The article does not talk about recording each real movement on the database. It talks about having a document with `who` is gonna make  `what` and `why`. Also this is only aplicable for companies with more than 250 employees. Recording the login and logout will not fulfill that requirements. Your interpretation of the law would require logging each movement with personal data, and that includes email, database records, etc.. 

At least, but not at last, the regulation always talk about *reasonable measures*, because not everyone can afford the costs of mantaining a huge log.

**Comment by Eseperio** [comment]
By now i know that GDPR requires
- [ ] Data portability
- [ ] Right to erasure (Right to be forgotten)
- [ ] Encryption of personal data (when possible but highly recommended. It can be acomplished with db encrypted hosting)
- [ ] Data processing consent
- [ ] Record of when was given consent
- [ ] Privacy policy with clear information
- [ ] Pseudonymisation
- [ ] Have SSL (data protection on transport)

**Comment by maxxer** [comment]
gdpr pr has been merged
