### ISSUE TITLE
Key "status" is not a column name and can not be used as a filter

### ISSUE THREAD

**Issue by khvalov** [2amigos/yii2-usuario#225]
New fresh installation says: 

```php
exception 'yii\base\InvalidArgumentException' with message 'Key "status" is not a column name and can not be used as a filter' in /private/var/www/vendor/yiisoft/yii2/db/ActiveRecord.php:218
Stack trace:
#0 /private/var/www/vendor/yiisoft/yii2/db/ActiveRecord.php(190): yii\db\ActiveRecord::filterCondition(Array)
#1 /private/var/www/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array)
#2 /private/var/www/common/models/User.php(64): yii\db\BaseActiveRecord::findOne(Array)
#3 /private/var/www/vendor/yiisoft/yii2/web/User.php(690): common\models\User::findIdentity(1)
#4 /private/var/www/vendor/yiisoft/yii2/web/User.php(192): yii\web\User->renewAuthStatus()
#5 /private/var/www/vendor/yiisoft/yii2/web/User.php(360): yii\web\User->getIdentity()
#6 /private/var/www/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIsGuest()
#7 /private/var/www/vendor/yiisoft/yii2-debug/panels/UserPanel.php(81): yii\base\Component->__get('isGuest')
#8 /private/var/www/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\panels\UserPanel->init()
#9 [internal function]: yii\base\BaseObject->__construct(Array)
#10 /private/var/www/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#11 /private/var/www/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\debug\\panel...', Array, Array)
#12 /private/var/www/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('yii\\debug\\panel...', Array, Array)
#13 /private/var/www/vendor/yiisoft/yii2-debug/Module.php(177): yii\BaseYii::createObject(Array)
#14 /private/var/www/vendor/yiisoft/yii2-debug/Module.php(149): yii\debug\Module->initPanels()
#15 /private/var/www/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\Module->init()
#16 /private/var/www/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#17 [internal function]: yii\base\Module->__construct('debug', Object(yii\web\Application), Array)
#18 /private/var/www/vendor/yiisoft/yii2/di/Container.php(375): ReflectionClass->newInstanceArgs(Array)
#19 /private/var/www/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\debug\\Modul...', Array, Array)
#20 /private/var/www/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('yii\\debug\\Modul...', Array, Array)
#21 /private/var/www/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#22 /private/var/www/vendor/yiisoft/yii2/base/Application.php(315): yii\base\Module->getModule('debug')
#23 /private/var/www/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#24 /private/var/www/vendor/yiisoft/yii2/base/Application.php(273): yii\web\Application->bootstrap()
#25 /private/var/www/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\base\Application->init()
#26 /private/var/www/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#27 /private/var/www/backend/web/index.php(17): yii\base\Application->__construct(Array)
#28 {main}
Copy Stacktrace Search Stackoverflow Search Google Exception
Invalid Argument – yii\base\InvalidArgumentException
Key "status" is not a column name and can not be used as a filter

**Comment by maxxer** [comment]
The error appears to be in your user model`common/models/User.php(64)` (ref number 2), not sure it's related to usuario

**Comment by Eseperio** [comment]
@khvalov, edit your message and use code tags. You have referenced 28 issues by using the hashtag and now a link to your message appears everywhere.

**Comment by LarryTX** [comment]
I'm having the very same problem. Of course, it may be related to the (not my) `common/models/User.php`. This is the model that is created by yiisoft when installing the advanced template. I have made no changes to that model, and so, the issue should be the same for all the folks with the advanced template. Since this appears to be the only user/rbac extension that is still maintained, it doesn't do much good to talk about the way that questioners formatted their issues or try to push their issue back onto something that is common to every single person who has installed the advanced template. We need an answer to the issue that was posed. Failing that, you just drive people away from Yii2 as fast as they can run.

Obviously, before I can put my website into production, I need to have a functioning user/rbac management system. I was hoping that 2amigos had one. I am still hoping that they do. I will repeat, when I attempt to go to `/user/registration/register`, I get the Invalid Argument message `Key "status" is not a column name and can not be used as a filter`. Can you give me any insight into how to fix this error? Any other comments you may have regarding my issue are secondary to the show-stopping issue with your extension. I welcome them — after we have resolved the problem with your extension. I repeat: This is a show-stopper.

**Comment by TonisOrmisson** [comment]
remove the 
```
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-backend', 'httpOnly' => true],
        ],
```

from components in `frontend/config/main.php` and `backend/config/main.php`

Btw. If its **your** application you are working on, then the `common/models/User.php` is obviously **your** model not **the** model. If you do not want to use the template user model and want to implement the usuario `User` model then you should kill the template version (means also in config)

**Comment by LarryTX** [comment]
No. That's not correct. Not at all. When you install yiis-advanced template via git clone from github, it automatically creates a User model **_in the common application_** that is part of the advanced template. It automatically creates **_/common/models/User.php_**. It creates the directories _/backend/models_ and _/frontend/models_, but there is nothing in them. Since I did not ever create /**_common/models/User.php_**. it is not _mine_. Now, as to the statement, "If you do not want to use the template user model and want to implement the usuario User model then you should kill the template version (means also in config)," I obviously must have missed that in the installation instructions. Or ... are you saying that, when using usario, I should simply delete everything in the entire directory created when cloning yii2-advanced, and assume that usario replaces everything?. Or just how far does that go? That's where good documentation goes. You take your documentation, give it to someone who barely even know what Yii2 is, and make sure that they can follow it to a successful conclusion. Then you do the same thing with a very expert Yii2 user.

**Comment by TonisOrmisson** [comment]
oh well ...

**Comment by yaronius** [comment]
Got the same error recently. Actually, the reason is trivial - DB table for identity model does not exist or has the wrong name. If you ever experience this error, try checking that `common\models\User::tableName()` returns correct name and that the table exists.

**Comment by wanjugu** [comment]
I also experienced the same error. I was able to solve it by using  @TonisOrmisson suggestion, 
 remove the

        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-backend', 'httpOnly' => true],
        ],

I also had to change the login  url in `backend\view\layouts\main.php' from 
$menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
to
$menuItems[] = ['label' => 'Login', 'url' => ['/user/login']];

**Comment by tonydspaniard** [comment]
Maybe is something we should document on the docs?

**Comment by amirkhan12345** [comment]
i got this error when proper field of user table was  not existing.

**Comment by Alkasih** [comment]
This is wtf 

`use backend\models\LoginForm;`
