### ISSUE TITLE
Error by using Events

### ISSUE THREAD

**Issue by skeeran** [2amigos/yii2-usuario#291]
### What steps will reproduce the problem?
```
require(__DIR__ . '/../config/events.php'); // <--- adding events here! :)

<?php 
// events.php file

use Da\User\Controller\AdminController;
use Da\User\Event\UserEvent;
use Da\User\Model\User;
use yii\base\Event;

// This will happen at the controller's level
Event::on(AdminController::class, UserEvent::EVENT_BEFORE_CREATE, function (UserEvent $event) {
    $user = $event->getUser();

}
```

### What is the expected result?
that the code modification works

### What do you get instead?
my whole page is not working anymore

**Comment by maxxer** [comment]
Please be more detailed. Where did you put the first line? 

In the `Event::on` block you're missing the closing parenthesis.

And *my whole page is not working anymore* is not a diagnostic message. It's probably a webserver internal server error, you should post the webserver error in order to understand

**Comment by maxxer** [comment]
What problem was that? For others to share, in case someone runs in the same

**Comment by maxxer** [comment]
I've fixed the examples

**Comment by maxxer** [comment]
> @maxxer it's still not fixed in the FormEvent :)

fixed :)
