### ISSUE TITLE
Disable creation of flash messages

### ISSUE THREAD

**Issue by maxxer** [2amigos/yii2-usuario#391]
Wondering if it's desirable as some requests were filed in the past. 
53209d2d78530c

Right now we only have the option to disable the displaying of flash messages but not the **creation**. Before wrapping all the `setFlash` into `if`s I'm wondering if there's some other way of trapping them.

**Comment by ajmedway** [comment]
It might make sense to have 2 separate config variables instead of the current `enableFlashMessages` one:

- `createFlashMessages` (bool)
- `displayFlashMessages` (bool)

This allows handling of the two separate concerns at play here e.g. giving ability to always create flash messages from within the module, then for different app configs having display from the template partial: 

src/User/resources/views/shared/_alert.php

or not, depending on how the app layout is built/configured.

**Comment by ajmedway** [comment]
For now, I am making a pull request that gives some consistency to always *create* flash messages (as is the case generally through out the module, except for in 2 places). The `enableFlashMessages ` config setting is handled within `src/User/resources/views/shared/_alert.php` for display purposes anyway.
